import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import getSession from "../../../../actions/verifySession";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const noLayoutRoutes = ["/projects/create", "/profile"]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = headers();
  const pathname = (await headerList).get("x-current-path") || '';
  const showLayout = !noLayoutRoutes.includes(pathname);
  console.log(pathname, "xddddddddddddddd")
  const isAuthenticated = await getSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {showLayout && <Navbar isAuthenticated={isAuthenticated?.isAuthenticated ?? true} />}
        {children}
        {showLayout && <Footer />}
      </body>
    </html>
  );
}
